config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :bookings, only: [:index]

  namespace :vendor do
    resources :bookings, only: [:index, :update]
    resources :cosplays, only: [:index]
  end

  resources :cosplays, only: [:index, :show, :create, :new] do
    resources :bookings, only: [:create, :new]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :cosplay

  validates :start_date, presence: true
  validates :end_date, presence: true

  validate :start_date_in_future, on: :create
  validate :end_date_in_future, on: :create
  validate :cannot_book_own_cosplay

  enum status: { pending: 'pending', accepted: 'accepted', rejected: 'rejected' }

  def start_date_in_future
    if start_date.present? && start_date <= Date.today
      errors.add(:start_date, "must be in the future")
    end
  end

  def end_date_in_future
    if end_date.present? && end_date <= start_date
      errors.add(:end_date, "must be later than the start date")
    end
  end

  def pending?
    status == 'pending'
  end

  def cannot_book_own_cosplay
    if user_id == cosplay.user_id
      errors.add(:base, "You cannot book your own cosplay item")
    end
  end
end

app/models/cosplay.rb
class Cosplay < ApplicationRecord
  belongs_to :user
  has_many :bookings
  #has_many :images, as: :imagebank
  has_many_attached :images
  validate :validate_image_count, on: :create

  SIZE = ['XS', 'S', 'M', 'L', 'XL']
  validates :size, presence: true
  validates :size, inclusion: { in: SIZE }
  validates :name, presence: true
  validates :source_material, presence: true
  validates :price, presence: true, numericality: { only_integer: true, greater_than: 0 }

  def validate_image_count
    if images.length > 3
      errors.add(:images, "You can only upload up to 3 photos")
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  has_many :cosplays
  has_many :bookings
  has_many :bookings_as_vendor, through: :cosplays, source: :bookings

  # validates :username, presence: true
  # validates :username, uniqueness: true
  # validates :email, presence: true
  # validates :password, presence: true
  # validates :address, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = current_user.bookings
  end

  def create
    @booking = Booking.new(booking_params)
    @cosplay = Cosplay.find(params[:cosplay_id])
    @booking.user = current_user
    @booking.cosplay = @cosplay
    if @booking.save
      redirect_to bookings_path
    else
      render "cosplays/show", status: :unprocessable_entity
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/cosplays_controller.rb
class CosplaysController < ApplicationController
  before_action :set_cosplay, only: [:show]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
      @cosplays = Cosplay.all
    @pagy, @cosplays = pagy(@cosplays, items: 20)
    if params[:query].present?
      sql_subquery = "name ILIKE :query OR source_material ILIKE :query"
      @cosplays = @cosplays.where(sql_subquery, query: "%#{params[:query]}%")
      # redirect_to cosplays_path(query:params[:query])
    end
    if params[:price_range].present?
      sql_subquery = "price >= ? AND price <= ?"
      @cosplays = @cosplays.where(sql_subquery, params[:price_range].split(",")[0].to_i, params[:price_range].split(",")[1].to_i)
    end
  end

  def show
    @cosplay = Cosplay.find(params[:id])
    @booking = Booking.new
  end

  def new
    @cosplay = Cosplay.new
  end

  def create
    @cosplay = Cosplay.new(cosplay_params)
    @cosplay.user = current_user
    if @cosplay.save
      redirect_to cosplay_path(@cosplay)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_cosplay
    @cosplay = Cosplay.find(params[:id])
  end

  def cosplay_params
    params.require(:cosplay).permit(:name, :size, :source_material, :price, images: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @cosplays = Cosplay.all
    @pagy, @cosplays = pagy(@cosplays, items: 20)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/bookings/_form.html.erb
<%# place holderfor booking form %>
<%= simple_form_for [@cosplay, @booking], html:{ data: { controller: 'totalprice' }} do |f| %>
  <%= f.input :start_date, html5: true, input_html:{data: { totalprice_target: 'startDate', action: 'change->totalprice#calculatePrice' }} %>
  <%= f.input :end_date, html5: true, input_html:{data: { totalprice_target: 'endDate', action: 'change->totalprice#calculatePrice' }} %>
  <div data-totalprice-target="unitPrice" data-totalprice-unitprice="<%= @cosplay.price %>"><%= @cosplay.price %> ¥ per Day</div>
  <div data-totalprice-target="daysDifference"></div>
  <% if @booking.errors.has_key?(:base) %>
    <div class="alert alert-danger">
      <% @booking.errors[:base].each do |error_message| %>
        <%= error_message %><br>
      <% end %>
    </div>
  <% end %>
  <%= f.button :submit, class: "text-white w-100 btn btn-primary my-3" %>
<% end %>

app/views/bookings/index.html.erb
<div class="container">
  <div class="w-50 m-auto mb-4 ">
    <h1 class="">Your Bookings</h1>
    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item" role="presentation">
        <button class="nav-link active" id="pending-tab" data-bs-toggle="tab" data-bs-target="#pending-tab-pane" type="button" role="tab" aria-controls="pending-tab-pane" aria-selected="true">Pending</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="accepted-tab" data-bs-toggle="tab" data-bs-target="#accepted-tab-pane" type="button" role="tab" aria-controls="accepted-tab-pane" aria-selected="false">Accepted</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="rejected-tab" data-bs-toggle="tab" data-bs-target="#rejected-tab-pane" type="button" role="tab" aria-controls="rejected-tab-pane" aria-selected="false">Rejected</button>
      </li>
    </ul>
  </div>
  <div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active" id="pending-tab-pane" role="tabpanel" aria-labelledby="pending-tab" tabindex="0">
      <% booking_count = 0 %>
      <% @bookings.pending.order(start_date: :asc).each do |booking| %>
        <% booking_count += 1 %>
        <div class="cosplay-show-card">
          <div class="d-flex justify-content-between">
            <h1 class="title m-0"><%= booking.cosplay.name %></h1>
            <p class="btn-booking align-self-center opacity-75">Status: <%= booking.status %></p>
          </div>
          <div class="carousel-container my-3">
            <div id="pictureCarousel<%= booking_count %>" class="carousel slide">
              <div class="carousel-inner">
                <%= render "cosplays/images", cosplay: booking.cosplay %>
              </div>
              <button class="carousel-control-prev" type="button" data-bs-target="#pictureCarousel<%= booking_count %>" data-bs-slide="prev">
                <div class="prev-next-button">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Previous</span>
                </div>
              </button>
              <button class="carousel-control-next" type="button" data-bs-target="#pictureCarousel<%= booking_count %>" data-bs-slide="next">
                <div class="prev-next-button">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Next</span>
                </div>
              </button>
            </div>
          </div>
          <div class="cosplay-info-and-booking-form d-flex justify-content-between">
            <div class="cosplay-info d-flex flex-column">
              <p>Source: <%= booking.cosplay.source_material %></p>
              <p><%= booking.cosplay.price %> ¥ / Per day</p>
              <p>Size: <%= booking.cosplay.size %></p>
              <p>From: <%= booking.start_date %>, To: <%= booking.end_date %></p>
              <% number_of_days = (booking.end_date - booking.start_date).to_i+1 %>
              <p>Number of days: <%= number_of_days %></p>
              <% total_price = number_of_days * booking.cosplay.price%>
              <p>Total price:<%= total_price %> ¥</p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="tab-pane fade" id="accepted-tab-pane" role="tabpanel" aria-labelledby="accepted-tab" tabindex="0">
      <% booking_count = 0 %>
      <% size = "M" %>
      <% @bookings.accepted.order(start_date: :asc).each do |booking| %>
        <% booking_count += 1 %>
        <div class="cosplay-show-card">
          <div class="d-flex justify-content-between">
            <h1 class="title m-0"><%= booking.cosplay.name %></h1>
            <p class="btn-booking align-self-center opacity-75">Status: <%= booking.status %></p>
          </div>
          <div class="carousel-container my-3">
            <div id="pictureCarousel<%= booking_count %>" class="carousel slide">
              <div class="carousel-inner">
                <%= render "cosplays/images", cosplay: booking.cosplay %>
              </div>
              <button class="carousel-control-prev" type="button" data-bs-target="#pictureCarousel<%= booking_count %>" data-bs-slide="prev">
                <div class="prev-next-button">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Previous</span>
                </div>
              </button>
              <button class="carousel-control-next" type="button" data-bs-target="#pictureCarousel<%= booking_count %>" data-bs-slide="next">
                <div class="prev-next-button">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Next</span>
                </div>
              </button>
            </div>
          </div>
          <div class="cosplay-info-and-booking-form d-flex justify-content-between">
            <div class="cosplay-info d-flex flex-column">
              <p>Source: <%= booking.cosplay.source_material %></p>
              <p><%= booking.cosplay.price %> ¥ / Per day</p>
              <p>Size: <%= booking.cosplay.size %></p>
              <p>From: <%= booking.start_date %>, To: <%= booking.end_date %></p>
              <% number_of_days = (booking.end_date - booking.start_date).to_i+1 %>
              <p>Number of days: <%= number_of_days %></p>
              <% total_price = number_of_days * booking.cosplay.price%>
              <p>Total price:<%= total_price %> ¥</p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="tab-pane fade" id="rejected-tab-pane" role="tabpanel" aria-labelledby="rejected-tab" tabindex="0">
      <% booking_count = 0 %>
      <% size = "M" %>
      <% @bookings.rejected.order(start_date: :asc).each do |booking| %>
        <% booking_count += 1 %>
        <div class="cosplay-show-card">
          <div class="d-flex justify-content-between">
            <h1 class="title m-0"><%= booking.cosplay.name %></h1>
            <p class="btn-booking align-self-center opacity-75">Status: <%= booking.status %></p>
          </div>
          <div class="carousel-container my-3">
            <div id="pictureCarousel<%= booking_count %>" class="carousel slide">
              <div class="carousel-inner">
                <%= render "cosplays/images", cosplay: booking.cosplay %>
              </div>
              <button class="carousel-control-prev" type="button" data-bs-target="#pictureCarousel<%= booking_count %>" data-bs-slide="prev">
                <div class="prev-next-button">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Previous</span>
                </div>
              </button>
              <button class="carousel-control-next" type="button" data-bs-target="#pictureCarousel<%= booking_count %>" data-bs-slide="next">
                <div class="prev-next-button">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Next</span>
                </div>
              </button>
            </div>
          </div>
          <div class="cosplay-info-and-booking-form d-flex justify-content-between">
            <div class="cosplay-info d-flex flex-column">
              <p>Source: <%= booking.cosplay.source_material %></p>
              <p><%= booking.cosplay.price %> ¥ / Per day</p>
              <p>Size: <%= booking.cosplay.size %></p>
              <p>From: <%= booking.start_date %>, To: <%= booking.end_date %></p>
              <% number_of_days = (booking.end_date - booking.start_date).to_i+1 %>
              <p>Number of days: <%= number_of_days %></p>
              <% total_price = number_of_days * booking.cosplay.price%>
              <p>Total price:<%= total_price %> ¥</p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/cosplays/_images.html.erb
<% if cosplay.images.any? %>
  <% cosplay.images.each_with_index do |image, index|%>
    <div class="carousel-item <%= "active" if index == 0 %>" style="background-image: url(<%= cl_image_path(image.key) %>);">
    </div>
  <%end%>
<% else %>
  <div class="carousel-item active" style="background-image: url(<%= image_url("https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Placeholder_view_vector.svg/681px-Placeholder_view_vector.svg.png") %>);">
  </div>
<% end %>

app/views/cosplays/index.html.erb
<div class="container">
  <h1 class=" mb-3 mt-5">All our Cosplays:</h1>
  <div class="d-flex justify-content-center">
    <div class="card-container">
      <% if @cosplays.any? %>
        <% @cosplays.each do |cosplay| %>
          <div class="card d-flex justify-content-center">
            <%= link_to cosplay_path(cosplay), class:"card-link" do %>
              <div class="homepage-card" style="background-image: url( <%= cosplay.images.attached? ? cl_image_path(cosplay.images.first.key) : image_url("https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Placeholder_view_vector.svg/681px-Placeholder_view_vector.svg.png") %> )">
                <div class="w-100"></div>
                <div class="d-flex flex-column w-100 info-text">
                  <h3 style="text-align: center"> <%= cosplay.name %> </h3>
                  <div class="d-flex justify-content-between pl-4 pr-4">
                    <p style="max-width: 45%"> <%= cosplay.source_material %> </p>
                    <p> ¥<%= cosplay.price %>/day </p>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
        <div class="last-card"></div>
        <div class="last-card"></div>
        <div class="last-card"></div>
      <% else %>
        <em>Sorry, no cosplays found!</em>
      <% end %>
    </div>
  </div>
  <div class="pag-bar mt-5 pt-5 d-flex">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
</div>

app/views/cosplays/new.html.erb
<div class="container">
  <div class="form-container">
    <h1>Add a Cosplay</h1>
    <%= simple_form_for @cosplay do |f| %>
      <%= f.input :name %>
      <%= f.input :source_material %>
      <%= f.input :price, input_html: { min: 0, step: 500} %>
      <%= f.input :size, as: :select, collection: Cosplay::SIZE %>
      <%= f.input :images, input_html: { multiple: true }, as: :file %>
      <%= f.button :submit, class: "btn btn-primary text-white w-100 my-3" %>
    <% end %>
  </div>
</div>

app/views/cosplays/show.html.erb
<div class="container mt-3">
  <div class="cosplay-show-card">
    <h1 class="title"><%= @cosplay.name %></h1>
    <div class="carousel-container my-3">
      <div id="pictureCarousel" class="carousel slide">
        <div class="carousel-inner">
          <%= render "cosplays/images", cosplay: @cosplay %>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#pictureCarousel" data-bs-slide="prev">
          <div class="prev-next-button">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </div>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#pictureCarousel" data-bs-slide="next">
          <div class="prev-next-button">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </div>
        </button>
      </div>
    </div>
    <div class="cosplay-info-and-booking-form">
      <div class="cosplay-info d-flex flex-column">
        <p>Source: <%= @cosplay.source_material %></p>
        <p><%= @cosplay.price %> ¥ / Per day</p>
        <p>Size: <%= @cosplay.size %></p>
    <%= render 'bookings/form' %>
      </div>

    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CosHub</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%# <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Anta&family=Kode+Mono:wght@400..700&display=swap" rel="stylesheet"> %>
  </head>
  <body style="background-color:#EFCFD">
    <div style="padding-bottom: 120px">
      <%= render "shared/navbar" %>
      <%= render "shared/flashes" %>
      <%= yield %>
      <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<%# <div class="banner">
  <div class="banner-text">
    <h1>CosHub</h1>
    <p>Cosplay delivery, to your door, lightning fast</p>
  </div>
</div> %>
<div class="curve">
  <svg width="100%" height="100%" id="svg" viewBox="0 0 1440 400" xmlns="http://www.w3.org/2000/svg" class="transition duration-300 ease-in-out delay-150"><path d="M 0,600 L 0,225 C 127.85714285714289,213.33928571428572 255.71428571428578,201.67857142857142 378,202 C 500.2857142857142,202.32142857142858 616.9999999999998,214.62499999999994 745,258 C 873.0000000000002,301.37500000000006 1012.2857142857144,375.8214285714286 1130,413 C 1247.7142857142856,450.1785714285714 1343.8571428571427,450.08928571428567 1440,450 L 1440,600 L 0,600 Z" stroke="none" stroke-width="0" fill="#D81159" fill-opacity="1" class="transition-all duration-300 ease-in-out delay-150 path-0" transform="rotate(-180 720 300)"></path></svg>
  <div class="banner-infos">
    <div class="banner-infos-left"></div>
    <div class="banner-infos-right">
      <h1 class="slogan">Book any cosplay you want with CosHub:</h1>
      <%= link_to "All our cosplays", cosplays_path(), class: "index-link btn btn-outline-warning"  %>
    </div>
  </div>
</div>
<%# <div class="banner">
</div> %>
<div class="container" style="z-index: 5; position: relative;">
  <h1 class="recent-cosplay-title mb-3">Most recent cosplays:</h1>
  <div class="d-flex justify-content-center flex-column">
    <div class="card-container">
      <% if @cosplays.any? %>
        <% @cosplays.each do |cosplay| %>
          <div class="card d-flex justify-content-center">
            <%= link_to cosplay_path(cosplay), class:"card-link" do %>
              <div class="homepage-card" style="background-image: url( <%= cosplay.images.attached? ? cl_image_path(cosplay.images.first.key) : image_path("logo.png") %> )">
                <div class="w-100"></div>
                <div class="d-flex flex-column w-100 info-text">
                  <h3 style="text-align: center"> <%= cosplay.name %> </h3>
                  <div class="d-flex justify-content-between pl-4 pr-4">
                    <p style="max-width: 45%"> <%= cosplay.source_material %> </p>
                    <p> ¥<%= cosplay.price %>/day </p>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      <% else %>
        <em>Nice website, shame nobody has uploaded to it</em>
      <% end %>
      <div class="last-card"></div>
      <div class="last-card"></div>
      <div class="last-card"></div>
    </div>
    <h1 class="recent-cosplay-title mb-3 mt-5">Some Cosplays for You:</h1>
    <div class="d-flex justify-content-center">
      <div class="card-container">
        <% if @cosplays.any? %>
          <% @cosplays.sample(8).each do |cosplay| %>
            <%= link_to cosplay_path(cosplay), class:"card-link" do %>
              <div class="homepage-card" style="background-image: url( <%= cosplay.images.attached? ? cl_image_path(cosplay.images.first.key) : image_url("https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Placeholder_view_vector.svg/681px-Placeholder_view_vector.svg.png") %> )">
                <h3> <%= cosplay.name %> </h3>
              </div>
            <% end %>
          <% end %>
          <div class="last-card"></div>
          <div class="last-card"></div>
          <div class="last-card"></div>
        <% else %>
          <em>Sorry, no cosplays found!</em>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a target="_blank" href="https://github.com/rubykytam"><i class="fab fa-github"></i></a>
    <a target="_blank" href="https://github.com/Nikita-Nagras"><i class="fab fa-github"></i></a>
    <a target="_blank" href="https://github.com/ntw3001"><i class="fab fa-github"></i></a>
    <a target="_blank" href="https://github.com/Jasufr"><i class="fab fa-github"></i></a>
  </div>
  <div class="footer-copyright">
    <a href="#">Privacy</a>・
    <a href="#">Terms</a>・
    <span>2024 CosHub,Inc.</span>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-light navbar-lewagon">
  <div class="container-fluid d-flex flex-nowrap">
    <div class="d-flex align-items-center">
      <%= link_to root_path, class: "navbar-brand d-flex align-items-center" do %>
        <%= image_tag "coshublogo.png" %>
        <h2 class="m-0 ms-3 text-light">CosHub</h2>
      <% end %>
    </div>
    <div class="d-flex justify-content-end">
      <%= form_with url: cosplays_path, method: :get, class: "search-form d-flex" do %>
        <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Search cosplays..."
        %>
        <%= select_tag(:price_range, options_for_select(([['¥', nil], ['¥0-2499', '0,2499'], ['¥2500-4999', '2500,4999'], ['¥5000-7499', '5000,7499'], ['¥7500-9999', '7500,9999'], ['¥10000-12499', '10000,12499'], ['¥12500-14999', '12500,14999'], ['¥15000-17499', '15000,17499'], ['¥17500-20000', '17500,20000']]), nil))%>
        <%= button_tag(type: 'submit', class: 'btn btn-primary') do %>
          <i class="text-light fa-solid fa-magnifying-glass"></i>
        <% end %>
      <% end %>
      <i class="fa-regular fa-bell d-flex align-items-center fs-5 ms-3 me-3"></i>
      <% if user_signed_in? %>
        <%# <li class="nav-item dropdown"> %>
        <%# <a href="#" class="ms-3" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> %>
        <button class="bg-light navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <%# </a> %>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
            <%# <div class="dropdown-menu dropdown-menu-end " aria-labelledby="navbarDropdown"> %>
            <li class="nav-item">
              <%= link_to "My Orders",  bookings_path, class: "dropdown-item" %>
            </li>
            <li class="nav-item">
              <%= link_to "My Products", vendor_cosplays_path, class: "dropdown-item" %>
            </li>
            <li class="nav-item">
              <%= link_to "Requests", vendor_bookings_path, class: "dropdown-item" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sell a cosplay", new_cosplay_path, class: "dropdown-item" %>
            </li>
            <li class="nav-item">
              <%= link_to "Settings", "#", class: "dropdown-item" %>
            </li>
            <li class="nav-item">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </li>
            <%# </div> %>
          </ul>
        </div>
        <%# </li> %>
      <% else %>
        <li class="nav-item ms-3 text-decoration-none">
          <%= link_to "Login", new_user_session_path, class: "btn btn-light login-button px-3" %>
        </li>
      <% end %>
    </div>
  </div>
</div>